<?php
/** @var \DataReporter\WebCare\Block\CookieBannerOptionsBlock $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = '';
if ($block->isCustomOptionsEnabled()) {
    $scriptString .= "    dr_cookiebanner_options.onStatusChange = function(status, chosenBefore) {
        if (status == 'allow') {
            {$block->getChildHtml('datareporter.webcare.cookiebanner.allow-handling')}
        } else if (status == 'deny') {
            {$block->getChildHtml('datareporter.webcare.cookiebanner.deny-handling')}
        }
    };
    ";
}

if ($block->isCustomRedirectAfterConsentEnabled()) {
    $scriptString .= "    dr_cookiebanner_options.onRedirectAfterConsent = function(option) {
        {$block->getChildHtml('datareporter.webcare.cookiebanner.redirect-after-consent')}
    };
    ";
}
$scriptString .= "    // show cookiebanner
    window.cookieconsent.initialise(dr_cookiebanner_options);";

/* @noEscape */
echo $secureRenderer->renderTag('script', [], $scriptString);
