<?php
/** @var \DataReporter\WebCare\Block\CookieBannerOptionsBlock $block */
?>
<script>
    <?php if ($block->isCustomOptionsEnabled()) { ?>
    dr_cookiebanner_options.onStatusChange = function(status, chosenBefore) {
        if (status == 'allow') {
            <?= $block->getChildHtml('datareporter.webcare.cookiebanner.allow-handling'); ?>
        } else if (status == 'deny') {
            <?= $block->getChildHtml('datareporter.webcare.cookiebanner.deny-handling'); ?>
        }
    };
    <?php } ?>
    <?php if ($block->isCustomRedirectAfterConsentEnabled()) { ?>
    dr_cookiebanner_options.onRedirectAfterConsent = function(option) {
        <?= $block->getChildHtml('datareporter.webcare.cookiebanner.redirect-after-consent'); ?>
    };
    <?php } ?>
    // show cookiebanner
    window.cookieconsent.initialise(dr_cookiebanner_options);
</script>